// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNs2SzBbT5cf46dZS4LrLV7iJYbp99mtE',
    appId: '1:700452135494:web:5e1f262240819e6a526047',
    messagingSenderId: '700452135494',
    projectId: 'my-todolist-2',
    authDomain: 'my-todolist-2.firebaseapp.com',
    storageBucket: 'my-todolist-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsM7r9_K3jbXGvJwgT7V1RhjHaiJpAlPg',
    appId: '1:700452135494:android:7a0af72f08fde023526047',
    messagingSenderId: '700452135494',
    projectId: 'my-todolist-2',
    storageBucket: 'my-todolist-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo5rNztCYmhnlbpxloI1Z3mhD1NcFqBVc',
    appId: '1:700452135494:ios:94c8a4ed6e3965d6526047',
    messagingSenderId: '700452135494',
    projectId: 'my-todolist-2',
    storageBucket: 'my-todolist-2.appspot.com',
    iosClientId: '700452135494-0ga9n35u2qt0pggr0n8di03qc28dfvcl.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo5rNztCYmhnlbpxloI1Z3mhD1NcFqBVc',
    appId: '1:700452135494:ios:94c8a4ed6e3965d6526047',
    messagingSenderId: '700452135494',
    projectId: 'my-todolist-2',
    storageBucket: 'my-todolist-2.appspot.com',
    iosClientId: '700452135494-0ga9n35u2qt0pggr0n8di03qc28dfvcl.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist2',
  );
}
